### ISSUE TITLE
Preserve case when creating file name for notes

### ISSUE THREAD

**Issue by tmalsburg** [zaeph/org-roam-bibtex#16]
I saw that the notes file created by `org-roam-bibtex-edit-notes` uses the lower-case version of the bibtex key + `.org`.  Preserving the case might be better because that would allow helm/ivy-bibtex to find the notes by simply setting `bibtex-completion-notes-path` to `org-roam-directory`.

**Comment by zaeph** [comment]
We're using Org-roam's `org-roam--title-to-slug` to generate the name of the files:
https://github.com/zaeph/org-roam-bibtex/blob/6bbdebb39d7edf9b369c16311afa18cf00cecffc/org-roam-bibtex.el#L493

I think this is safe to drop this, but I'm going to run some tests first.

**Comment by myshevchuk** [comment]
@tmalsburg Just don't use ${slug} in your title. 

1. You can use the citekey directly like this:
``` elisp
(setq org-roam-bibtex-preformat-templates t
      org-roam-bibtex-preformat-keywords '(("citekey" . "=key="))
      org-roam-bibtex-templates
                '(("r" "ref" plain #'org-roam-capture--get-point
                   "%?"
                   :file-name "references/${citekey}"
                   :head "#+TITLE: ${title}\n#+ROAM_KEY: ${ref}\n"
                   :unnarrowed t)))
```
2. Above, the difference between "citekey" and "ref" is that the latter is a kind of hardcoded internal and will be formatted according to the format specified in `org-roam-bibtex-citekey-format` (`cite:%s` by default, if it's `nil` then "ref" is the citekey). So the following will also work yielding the identical result:

```  elisp
(setq org-roam-bibtex-preformat-templates nil
      org-roam-bibtex-citekey-format nil
      org-roam-bibtex-preformat-keywords nil
      org-roam-bibtex-templates
                '(("r" "ref" plain #'org-roam-capture--get-point
                   "%?"
                   :file-name "references/${ref}"
                   :head "#+TITLE: ${title}\n#+ROAM_KEY: cite:${ref}\n"
                   :unnarrowed t)))
```

3. Alternatively, the same result can be achieved with `org-roam-capture-templates` (to use these one must set `org-roam-bibtex-templates` to `nil`, however). 

``` elisp
(setq org-roam-capture-templates 
        '(("r" "reference" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "references/${citekey}"
           :head "#+TITLE: ${title}\n#+ROAM_KEY: cite:${citekey}\n"
           :unnarrowed t)))
```
4. Note that extra things in `:head` can be moved into the template string (5th element of the list). For preformatting to take place one has to use Org-capture's `%^{...}` syntax instead of `${...}` used in `:file-name` and `:head`, which are Org-roam's add-ons to Org-capture.

``` elisp
(setq org-roam-capture-templates 
        '(("r" "reference" plain (function org-roam-capture--get-point)
           "#+ROAM_KEY: cite:%^{citekey}\n%?"
           :file-name "references/${citekey}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t)))
```

5. Pay attention that in order to use custom bibtex-aware wildcards in the templates, make sure `org-roam-bibtex-preformat-templates` is `t` and the bibtex key field is set for preformatting:

``` elisp
(setq org-roam-bibtex-preformat-keywords "=key=")
(setq ... templates ...
...  :file-name "${=key=}" ...
```
or

``` elisp
(setq org-roam-bibtex-preformat-keywords '(("myverybestcitekey" . "=key=")))
(setq ... templates ...
...  :file-name "${myverybestcitekey}" ...
```

By the way, this works with any bibtex field as retrieved by `bibtex-completion-apa-get-value`. As far as I'm aware, only "citekey" and "type" fields have special names, `=key=` and `=type=`, respectively. All other field names are the same as found in a `bib` file. So one can put anything or even everything from a bibtex record into the notes file and the file name itself!

With this setup Bibtex-completion has worked out of the box from the very beginning 😉

**Comment by zaeph** [comment]
Thanks for double-checking this, @myshevchuk!
I'm not sure if we should make `(setq org-roam-bibtex-preformat-keywords '(("citekey" . "=key="))` anvec `:file-name "${citekey}"` the defaults, though.  As it is right now, it prevents special characters from screwing up with the file-creation.

**Comment by myshevchuk** [comment]
@zaeph Yes, a similar thought appeared to me. Could you please make a separate issue for this. I'd opt for the defaults you are suggesting. As of now, `org-roam-capture-templates` and `org-roam-bibtex-templates` provide basically the same functionality and interface. We could tune `org-roam-bibtex-templates` to be more user friendly.
