### ISSUE TITLE
Vritual BibTeX field "author-abbrev" doesn't work in capture template

### ISSUE THREAD

**Issue by tmalsburg** [zaeph/org-roam-bibtex#20]
This field contains an abbreviated version of the authors, e.g. "Doe et al.".

Haven' tested but I suppose `author-or-editor` doesn't work either.

I don't fully understand how the template is filled but perhaps you could follow the approach used in `bibtex-completion-fill-template`.  This would make all fields, virtual or not, available for use in capture templates.

Side note: I saw this use of `s-format` in two places:

``` elisp
(s-format "${title}" 'bibtex-completion-apa-get-value entry)
```
This should be equivalent to:
``` elisp
(bibtex-completion-apa-get-value "title" entry)
```

**Comment by zaeph** [comment]
> This field contains an abbreviated version of the authors, e.g. "Doe et al.".
> 
> Haven' tested but I suppose `author-or-editor` doesn't work either.

Both of them actually work, but you have to allow their expansion explicitly in `org-roam-bibtex-preformat-keywords`:
```el
(setq org-roam-bibtex-preformat-keywords '(("citekey" . "=key=")
                                           "author-abbrev"
                                           "author-or-editor"))
```
We use `bibtex-completion-apa-get-value` for the expansion, so it'll behave as you expect.

Also, whilst testing, I noticed that running `(bibtex-completion-apa-get-value 'author-abbrev …)` on an entry that does not have an author produces an error instead of failing silently.  I'm not sure if this is new, but I don't remember encountering that issue before.

> I don't fully understand how the template is filled but perhaps you could follow the approach used in `bibtex-completion-fill-template`. This would make all fields, virtual or not, available for use in capture templates.

`org-roam-bibtex--preformat-template` is the function you want to look at if you want to see how we're handling the expansion, but I'll readily admit this is quite complex. @myshevchuk did a great job of commenting the code, so they should be lanterns amidst the dark for you.

> Side note: I saw this use of `s-format` in two places:
> 
> ```emacs-lisp
> (s-format "${title}" 'bibtex-completion-apa-get-value entry)
> ```
> 
> This should be equivalent to:
> 
> ```emacs-lisp
> (bibtex-completion-apa-get-value "title" entry)
> ```

This looks equivalent indeed.  I'll do some sweeping.

**Comment by tmalsburg** [comment]
> Both of them actually work, but you have to allow their expansion explicitly in org-roam-bibtex-preformat-keywords:

I hope you don't mind if I ask, but why is it necessary to explicitly allow certain keywords?  Why not allow all by default?

> Also, whilst testing, I noticed that running (bibtex-completion-apa-get-value 'author-abbrev …) on an entry that does not have an author produces an error instead of failing silently.

You have to provide the field name as a string, not as a symbol, but, yes, it's possible that I don't deal with the case where no author exists.

> org-roam-bibtex--preformat-template is the function you want to look at if you want to see how we're handling the expansion, but I'll readily admit this is quite complex.

I did look at this function but didn't really understand why this complexity was necessary. But that's probably just because I didn't spend enough time, so feel free to ignore.

**Comment by zaeph** [comment]
> I hope you don't mind if I ask, but why is it necessary to explicitly allow certain keywords? Why not allow all by default?

It's because we don't want to completely shadow `org-roam-capture--fill-template` from upstream:
```
org-roam-capture--fill-template is a Lisp closure in ‘org-roam-capture.el’.

(org-roam-capture--fill-template STR &optional INFO)

Expands the template STR, returning the string.
This is an extension of org-capture’s template expansion.

First, it expands ${var} occurrences in STR, using the INFO alist.
If there is a ${var} with no matching var in the alist, the value
of var is prompted for via ‘completing-read’.

Next, it expands the remaining template string using
‘org-capture-fill-template’.
```

I think the problem was that we wanted to ensure that we didn't expand variables which were meant to be expanded by `org-roam-capture--fill-template` such as `${title}` which would have different meaning based on the _moment_ in the expansion (i.e. ORB's vs OR's).

> You have to provide the field name as a string, not as a symbol, but, yes, it's possible that I don't deal with the case where no author exists.

Whoops, yeah, sorry, copied it from memory, but the problem occurred with a string.

> I did look at this function but didn't really understand why this complexity was necessary. But that's probably just because I didn't spend enough time, so feel free to ignore.

I think the template expansion is the main reason for it.  @myshevchuk took care of this section of the code, so you might want to ask him for details if the comments aren't making it sufficiently clear.

**Comment by tmalsburg** [comment]
Thanks for these explanations!

**Comment by myshevchuk** [comment]
@tmalsburg 
> `(s-format "${title}" 'bibtex-completion-apa-get-value entry)`
> `(bibtex-completion-apa-get-value "title" entry)`

Thank you for pointing this out. Sometimes it's hard to escape from a certain paradigm.

Regarding the main question, the template expansion deals with interactive prompts making them non-interactive by filling them with values from a bibtex record.

Specifically, two types of prompts are addressed: org-capture's `%^{citekey}` and a more general one `${citekey}` used in `:head` and `:file-name`. Unfortunately, `bibtex-completion-fill-template` will not work here because we want to make interactive prompts non-interactive.
Just try to evaluate this:
``` elisp
(org-capture-fill-template "%^{citekey}")

or

(bibtex-competion-fill-template "%^{citekey}")
```
You'll be presented with a prompt. And if one doesn't want a prompt, then the template must be "preformatted". After studying `org-capture-templates` options I didn't find a way to input arbitrary variables other than through interactive prompts.

`bibtex-completion-fill-template` will of course handle `${citekey}` in `:head` and `:file-name` but there is currently very little gain if any in using it, because that part of `org-roam-bibtex--preformat-template` is essentially as simple as
 `(s-replace rplc-s2 field-value head)` and `(s-replace rplc-s2 field-value fl-nm)`

Of course, one could have `${citekey}` in the org-capture template string and run a `fill-template` function on it but:
1) this started as a small hack for `org-roam-capture-templates` to deal with interactive prompts before `org-roam-bibtex` was conceived;
2) such syntax, although harmless, does not comply with `org-capture-templates` specifications
3) a user is given a choice: one day they may want to fill their templates automatically, another day 
they'd prefer an interactive prompt. 
4) @zaeph is right, it's not our business to deal with `org-capture-templates` in general, only with the part relevant to bibtex, the rest should be done by `org-roam-capture`. That's why templates are "preformatted" rather than fully expanded.
5) such changes could probably be a part of new `org-roam-bibtex-templates` once they are ready, see #18. Currently we support vanilla `org-roam-capture-templates` and have our own`org-roam-bibtex-templates`, which are almost identical both functionality- and UI-wise.

The perceived complexity of `org-roam-capture--fill-templates` is due to the fact that we also need to expand numbered matches. If you have Doe2020 as a citekey and a template string like this:
```
"#ROAM_KEY: %^{citekey}
some text
\fullcite{%\\1}
```
it will be expanded to

```
"#+ROAM_KEY: Doe2020
some text
\fullcite{Doe2020}
```
Again, this was done for a full compatibility with `org-capture-templates` and may be a subject to changes in new `org-roam-bibtex-templates`.

**Comment by myshevchuk** [comment]
@tmalsburg thank you for your input!

**Comment by zaeph** [comment]
@myshevchuk Thanks for taking the time to walk us through the pre-formatting.  I think we might add those implementations notes in the manual at some point, but since nothing is set in stone right now, it might be best to hold off until it is.
